# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68af7202044f16d7b407f0eee22005c97f13fe2b684555dbb3d8f724e1145397fa78764d1af1b5cb84f889b2cecac888fb304167e06f0a164e6045168ebdfed

test:
  secret_key_base: 4e127a3582de9d545c0f09d0827d45eeee3b9e200e961fb009df89cdebcd6565e95ca7e6d2e5bb14047a041bdb2ea7a666f8474e34b49b5b3440e949ff5f29cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
